template: Hello, %s!
defaultName: Stranger

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://127.0.0.1:3306/dropwizard?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

  properties:
      charSet: UTF-8
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  maxWaitForConnection: 1s

  validationQuery: SELECT 1

  minSize: 8

  maxSize: 32

  checkConnectionWhileIdle: false
